[#33] Home의 기존 앨범 버튼을 상품관리 버튼으로 변경
Yoonkeee/dev-sosweet pull request #34
Opened 2024-09-01 11:28 UTC by k-jeonghee

## Description
- 상품관리 버튼 홈 페이지에 추가

## What type of PR is this?
- [X] 🍕 Feature

### 작업된 화면
![issue-33](https://github.com/user-attachments/assets/6009f202-5941-4fc9-a918-5ea5feec5725)

## Issue
close #33

2024-09-01 11:29 UTC, k-jeonghee commented
윤기님 이슈 33번 PR 올립니다~!
상품관리 버튼을 추가하면서 위치상 댕댕이 정보 수정 버튼 아래로 오는게 좋을 것 같아 위치도 함께 수정했습니다!

2024-09-01 13:59 UTC, Yoonkeee requested changes

2024-09-01 13:59 UTC, Yoonkeee commented on frontend/src/routes/Home.jsx
> +        title="상품관리"
기존에 글자가 '앨범' 두글자였을 때에는 프로 사진이랑 글자가 겹치지 않아서 시인성이 좋았는데,

프로 위로 글자가 겹치니까 시인성이 너무 안좋아졌어요. 잘 보이는 컬러로 변경해주시면 좋을 것 같아요.

어떤 색이 좋을지는 각 색의 HEX를 입력하여 어울리는 배합을 찾아볼 수 있는 좋은 사이트들이 있습니다!

2024-09-02 10:27 UTC, k-jeonghee commented on frontend/src/routes/Home.jsx
> +        title="상품관리"
흰색보다 조금 더 부드러운 색상으로 변경해보았습니다!

### 적용화면
<p>
<img src="https://github.com/user-attachments/assets/4371eff6-95d5-4f67-9fdc-0f82dbe6cd6a" width="360px"/>
</p>

2024-09-02 12:52 UTC, Yoonkeee commented on frontend/src/routes/Home.jsx
> +        title="상품관리"
그것도 좋은 방법일 것 같아요! 이대로 머지하셔도 되고 이미지 더 옮기셔도 될 것 같아요. 셀프 머지 해주세요~

2024-09-02 12:52 UTC, Yoonkeee approved these changes

2024-09-03 01:08 UTC, merged